### ISSUE TITLE
photos.py .MOV orientation

### ISSUE THREAD

**Issue by bobhavlin** [picklepete/pyicloud#118]
Any idea how to correct the upside down nature of a video downloaded through:

download = api.photos.all[i].download('original')

When viewed in icloud, the .MOV have the correct orientation.  I'm guessing the EXIF orientation tag is omitted in the api.photos.download('original').

**Comment by torarnv** [comment]
The orientation should be part of the extended data of the original file, so Finder/Preview should be able to view it correctly. Does it not? Or are you seeing the video upside down in an other application? 

There is some orientation metadata along with each photo that we get from iCloud, but I was under the assumption it was just redundant data so that the iCloud web interface would be able to show previews correctly without reading the full file.

**Comment by bobhavlin** [comment]
Yes, the EXIF orientation is not in the file downloaded.   It is upside down when viewed in VLC, etc.  I just tested icloud again, when the same is downloaded using the "download selected items" through icloud (presumably this is the "original" format), it is upside down, but when downloaded through the viewer (presumably "large" format in pyicloud) it has correct orientation.  I'll test it later today.  Thanks for the response.

**Comment by torarnv** [comment]
Can you try exporting a mov file from your phone and verify that it has the exif data and plays correectly in VLC, and then add it to iCloud and see if iCloud possibly strips some data from the "original"?

**Comment by bobhavlin** [comment]
Just tried what you suggested  (apparently you cannot upload videos through web icloud), but I think I have figured out what is going on.  When I play the video in quicktime, no matter where it comes from (pyicloud, icloud, or phone) it has the correct orientation, VLC not so.  Thus, the orientation info is there and no fault on pyicloud's part.  Thanks for the help and sorry for the distraction.
