### ISSUE TITLE
Max retries exceeded with url:

### ISSUE THREAD

**Issue by itadder** [picklepete/pyicloud#136]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p32-photosws.icloud.com',
.icloud.com', port=443): Max retries exceeded with url:

any idea

**Comment by chadj** [comment]
Not much to add here but I'm also running into this problem.

**Comment by chadj** [comment]
I have a feeling Apple released a non-backwards compatible change to the iCloud end points.  Just doing some basic inspection on the network calls for the web interface I'm not seeing any calls to the Photos webservice url.  Instead, it appears as though photo information is being retrieved with calls like:

https://p26-ckdatabasews.icloud.com/database/1/com.apple.photos.cloud/production/private/records/query

Maybe I'm wrong?

**Comment by itadder** [comment]
Oh so they have not blocked my use ?

**Comment by chadj** [comment]
@itadder no I don't believe so

I started banging some stones together here [chadj/pyicloud/ckdatabasews](/chadj/pyicloud/tree/ckdatabasews) on an update to support these end point changes.  Its super rough.

**Comment by torarnv** [comment]
Ouch :/

**Comment by itadder** [comment]
any updates on this issue?

Thanks

**Comment by chadj** [comment]
Ok the [chadj/pyicloud/ckdatabasews](/chadj/pyicloud/tree/ckdatabasews) branch isn't so rough any more.  It's "mostly" a drop-in replace for the old PhotosService implementation.  With a few exceptions / outstanding issues

- I'm not sure how the new API handles uninitialized Photo libraries
- I'm not sure if PhotoService.update() ( or a similar call ) is necessary any more.
- Rapid fire invocations of a containing script causes the following error: ```PyiCloudAPIResponseError: private db access disabled for this account```  This only seems to indicate that the remote endpoint is attempting to throttle requests.  If you wait 60 seconds or so the problem will go away.  I haven't figured out if there's a programatic way around this yet.  Long running scripts aren't a problem but running the same script repeatedly causes this error to crop up.
- `PhotoAsset.versions` the "large" option is no longer available.
- `PhotoAsset.versions` entry.mimetype no longer available.  Instead an entry.type option is available that indicate type but it's not a mimetype.
- `PhotoAsset.title` and `PhotoAsset.description` no longer available 
- `PhotoAsset.cliend_id` no longer available.  `PhotoAsset.id` is its replacement but represents a different unique value
- The new endpoints are much more flexible than the old ones.  We should expose some of that functionality (i.e. paging and sorting the data)
- Somewhat unrelated, I think this commit bda08319fc3c02561c82743267823c19bf3e9495 is going to cause a compatibility issue with [ndbroadbent/icloud_photos_downloader](/ndbroadbent/icloud_photos_downloader).  Which might be ok, because I was thinking about also making a breaking change to `PhotoAlbum.photos` to have it return a generator v.s. a list.

In general it needs more testing, but it does work.  If you're feeling adventurous give that branch a shot.

**Comment by chadj** [comment]
I did forget to mention one more incompatibility:

- `PhotoAsset.created` doesn't exactly match the previous value returned by the old endpoints.  Even when accounting for the TZ adjustments from bda08319fc3c02561c82743267823c19bf3e9495 it can differ up to a few seconds per image.  Unfortunately I don't see a way around this.

**Comment by itadder** [comment]
Thanks will give it a try.

**Comment by xuurukefi** [comment]
@chadj Do you have any idea how to reverse engineer the ubiquity endpoint, since it is not working anymore either (see #135)? I checked the webinterface, but it doesn't seem like there is a frontend for it.

**Comment by itadder** [comment]
Chadj I still getting this message with your branch. Max retries exceeded with url: /ph/startup?clientBuildNumber please let me know what I could be doing wrong.

''' photos = api.photos.all
selfies = api.photos.albums['selfies']
photos_count = len(photos)
selfies_count = len(selfies)

print("I have %s photos and %s seflies." % (photos_count, selfies_count)) '''

**Comment by chadj** [comment]
@xuurukefi I definitely need some web calls to inspect to do any sort of reverse engineering.

@itadder how did you install my branch?  I have a feeling you're still running the old version.

**Comment by chadj** [comment]
FYI,
  To install that branch:

```
$ pip uninstall pyicloud
$ pip install git+https://github.com/chadj/pyicloud.git@ckdatabasews
```

Also it looks like Apple no longer supports the 'selfies' smart album via the web interface.  But the follow smart albums are supported

```
['Time-lapse', 'Recently Deleted', 'Videos', 'Slo-mo',
 'All Photos', 'Live', 'Bursts', 'Favorites', 'Panoramas',
 'Hidden', 'Screenshots']
```

**Comment by itadder** [comment]
chadj it is working now, I had uninstalled the wrong branch.
By the way great job on getting this working again. 
Thanks again.

**Comment by abotsis** [comment]
This branch worked for me. I'm doing a sync of ~13000 JPGs/raw/video right now, and it's chugging right along. I made a few small tweaks to `icloud_photos_downloader`, if anyone needs it let me know and I'll fork it. Thanks for the patch!

**Comment by jamescarlos** [comment]
@abotsis i'd be interested in knowing what tweaks you made.

**Comment by abotsis** [comment]
@jamescarlos 
Here's my fork: https://github.com/abotsis/icloud_photos_downloader
These are the minimum amount of changes to make things work - there's still some brokenness, or at least things that should be done differently. Off the top of my head:

- Providing a range doesn't work because the photo list is a generator now. If I thought more about it, I would have at least tried to do something like `photos = list(icloud.photos.all.photos)`. I suspect it might be faster with a higher up-front penalty. 

Actually, that's all I can think of. There is a non-related "bug" in that RAW image files  (with a .CR2 extension in my case) won't download unless you also download videos.

**Comment by chadj** [comment]
I've been working on an update to [ndbroadbent/icloud_photos_downloader](/ndbroadbent/icloud_photos_downloader) over in ndbroadbent/icloud_photos_downloader#23.  You can find more info over in that issue.

**Comment by ndbroadbent** [comment]
Hi @chadj, thanks a lot, I've been testing the changes on your branch and everything seems to work great!

**Comment by hadiasghari** [comment]
@ndbroadbent will you be releasing a new https://github.com/ndbroadbent/icloud_photos_downloader based on the changes?

**Comment by nicoh88** [comment]
@abotsis 
Your fork works good - thank you.
But ...

`Downloading 9759 original photos and videos to /mnt/data/private/...
All photos have been downloaded!
Deleting any files found in 'Recently Deleted'...
Traceback (most recent call last):
  File "./download_photos.py", line 204, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 108, in download
    created_date = parse(media.created)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 192, in split
    return list(cls(s))
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 61, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not datetime`

@ndbroadbent 
Will you be releasing a new version based on the changes from abotsis?

**Comment by chadj** [comment]
@nicoh88 [ndbroadbent/icloud_photos_downloader](/ndbroadbent/icloud_photos_downloader) has been updated.  Give your local repo an update.

**Comment by torarnv** [comment]
https://github.com/picklepete/pyicloud/pull/137 has been merged, keep testing, I'll cut a new release in a week if things look okey.

**Comment by torarnv** [comment]
Great work @chadj !!

**Comment by chadj** [comment]
I tested master today, and it seems to be working great.

**Comment by torarnv** [comment]
Great!
