### ISSUE TITLE
Python Beginner

### ISSUE THREAD

**Issue by RonSwanson299** [picklepete/pyicloud#210]
Hello, I am new to using Python for API services and would appreciate some help if anyone is willing to lend a hand.  I have been racking my brain on how to get this started, but I cant seem to be able to figure it out.  If someone would be willing to share their code to access iCloud (Notes/Calendar/or Photos) I would be very grateful. Im sure I am missing a few steps, but like I said I am very new to this. Thank you!

**Comment by Quentame** [comment]
Hi !

What to you have so far ?

I've made some devs here : https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/icloud

Initialization here : https://github.com/home-assistant/home-assistant/blob/a1e1610a697efc6b4a25692358742a92f031ff4a/homeassistant/components/icloud/account.py#L95

Looking at other PR might also helps.

If it can help.

I'm closing the issue since it's not an issue but if you answer I will respond.
