### ISSUE TITLE
This project seems to be abandoned. Is there a preferred fork?

### ISSUE THREAD

**Issue by zefoo** [picklepete/pyicloud#222]
I'm not too familiar with this situation but thought someone here may be able to help...

It would seem this project is abandoned and no longer maintained. In Github land, I believe the only other option here is to find someone with a preferred fork who is actively maintaining this. 

I see this project has been forked 222 times. Is there anything that indicates a preferred fork that I should use that has things like Reminders in iOS 13 fixed or Find My Friends fixed? It's also possible neither of these are fixed, but given the fragmentation around this project I thought someone here may have more insight (and possibly has resolved this). 

It's also possible there is some way to pull an update from this project that's "dev" which the original author hasn't officially approved or such... in which case, how/where is that? I'm not too familiar with the Github ecosystem or situations like this. Grateful for any insight, thank you.

**Comment by RussellCofIdaho** [comment]
I am interested and following, hopefully something comes of it.

**Comment by Quentame** [comment]
I am the main maintainer of this project starting from a month ago.

Making new PRs and trying to merge very old ones, while testing first.
Personally using it in https://github.com/home-assistant/home-assistant

This project is the best I think, you have you use it ?
Try to use it and don’t hesitate to open new issues or PRs !
You can tag me if you want 😉

So, closing this issue since it’s not one 😝

I will have time in two weeks to do deeply on issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
