### ISSUE TITLE
findmyiphone.py not always returning battery level?

### ISSUE THREAD

**Issue by Bart274** [picklepete/pyicloud#56]
Hi,

Is there a reason why the findmyiphone.py isn't always returning the battery level?
pyicloud is used in Home Assistant to track the device of my account and of the account of my girlfriend.
When I look at the data I receive, my battery levels of both my iPhone and iPad are being received, but the battery levels of both my girlfriends iPhone and iPad aren't being received at all.
Her account used to be linked to my family on iCloud and then I could see her battery levels as well.
The reason I removed her account from my family is because I want to update my data each 5 minutes and hers only each 15 minutes (my iPhone is plugged in at work, hers isn't).

**Comment by coddingtonbear** [comment]
It will return all of the data that Apple's API returns to pyicloud's request.  I'm afraid it's very unlikely for anybody here to know why that specific field might not be returned from the API unless they accidentally happened upon the same problem.

Good luck, though!

**Comment by coddingtonbear** [comment]
@Bart274: I hope you don't mind that I'm closing this issue.  You can feel free to ask around in the [gitter channel](https://gitter.im/picklepete/pyicloud) to see if anybody else has bumped into the same issue, but since what data your device sends to iCloud is in Apple's hands and nobody working on this project (as far as I'm aware) works for Apple, your question might be better posed to Apple's forums themselves.

Cheers!

**Comment by Bart274** [comment]
I just asked here hoping it could be solved in this library and that it's not a fault of Apple, because I can see the battery levels of those devices on icloud.com.
I'll look further on internet, because the gitter channel isn't used a lot...
